{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq-tester.serviceAccountName" . }}-consumer
  labels:
    {{- include "rabbitmq-tester.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq-tester.serviceAccountName" . }}-producer
  labels:
    {{- include "rabbitmq-tester.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
