{{- if .Values.metrics.alertmanagerEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "node-dns-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-dns-exporter.labels" . | nindent 4 }}
    alertmanager: {{ .Values.alertManager | default "default" }}
spec:
  groups:
  - name: NodeDNS
    rules:
    - alert: NodeDNSerror
      annotations:
        message: |-
          {{`{{$labels.host}} is unreachable by {{$labels.pod}}({{$labels.node}}) in namespace: {{ $labels.namespace }}`}}
      expr: 'sum(node_dns_test_result{status="failed"}>0) BY (host,namespace,pod,node)'
      for: {{ .Values.alertFor | default "3m" }}
      labels:
        serverity: warning
{{- if .Values.customAlertRules }}
{{ toYaml .Values.customAlertRules | indent 4 }}
{{- end }}
{{- end }}
