appEnv: production
appVersion: v1

job:
  name: "schedule-job-001"
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  #  Allow (default): The cron job allows concurrently running jobs
                             #  Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
                             #  Replace: If it is time for a new job run and the previous job run hasn't finished yet, the cron job replaces the currently running job run with a new job run
  args:
    - /bin/sh
    - -c
    - date; echo Hello from the Kubernetes cluster
  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"] 

image:
  repository: ""
  tag: ""
  # pullSecrets:
  #   - secret1
  #   - secret2

