{{- if .Values.alertRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.metaLabels" . | nindent 4 }}
    alertmanager: {{ .Values.alertManager | default "default" }}
spec:
  groups:
{{ toYaml .Values.alertRules | indent 4 }}
{{- end }}