{{- if .Values.alertRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
    alertmanager: {{ .Values.alertManager | default "default" }}
spec:
  groups:
{{ toYaml .Values.alertRules | indent 4 }}
{{- end }}