{{- $hosts := .Values.cert.hosts -}}

{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
{{ $hosts = .Values.istio.ingress.hosts }}
{{- else if .Values.ingress.enabled }}
{{ $hosts = .Values.ingress.hosts }}
{{- end }}

{{- if and .Values.cert.enabled ($hosts) }}

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "golang.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "golang.name" . }}
    chart: {{ template "golang.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
  annotations:
{{ toYaml .Values.cert.annotations | indent 4 }}
spec:
  acme:
    config:
    - dns01:
        provider: {{ .Values.cert.acmeDnsProvider }}
      domains:
{{ $hosts | toYaml | indent 8 }}
  commonName: {{ index $hosts 0 }}
  dnsNames:
{{ $hosts | toYaml | indent 4 }}
  issuerRef:
    kind: {{ .Values.cert.issuerKind | default "ClusterIssuer" }}
    name: {{ .Values.cert.issuer | default "letsencrypt-prod" }}
  secretName: {{ template "golang.name" . }}-tls
{{- end }}