
{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
{{ $hosts = .Values.istio.ingress.hosts }}
{{- else if .Values.ingress.enabled }}
{{ $hosts = .Values.ingress.hosts }}
{{- end }}

{{- if and .Values.cert.enabled ($hosts) }}

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
  annotations:
{{ toYaml .Values.cert.annotations | indent 4 }}
spec:
  secretName: {{ .Values.ingress.tlsSecretName }}
{{- if .Values.cert.duration }}
  duration: {{ .Values.cert.duration }}
{{- end }}
  renewBefore: {{ .Values.cert.renewBefore }}
  commonName: {{ (index $hosts 0).host }}
  dnsNames:
  {{- range $hosts }}
  -  {{ .host }}
  {{- end }}
  issuerRef:
    name: {{ .Values.cert.issuer | default "letsencrypt-prod" }}
    kind: {{ .Values.cert.issuerKind | default "ClusterIssuer" }}
{{- end }}