
{{- if .Values.istio.serviceentry }}
{{- $name := include "libchart.name" . }}
{{- $labels := include "libchart.labels" . }}
{{- $chart := include "libchart.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $serviceentry := .Values.istio.serviceentry }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{ $name }}-{{ $serviceentry.name }}"
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  {{- toYaml $serviceentry.spec | nindent 2 }}
{{- end }}

{{- end }}
