{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.metaLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 8 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}