{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "web.name" . }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "web.name" . }}
      chart: {{ template "web.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      version: {{ .Values.appVersion }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}