{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
type: Opaque
data:
{{ toYaml .Values.secrets.data | indent 2 }}
{{- end }}