{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
    labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
