apiVersion: v1
kind: Service
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.metaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}