apiVersion: v1
kind: Service
metadata:
  name: {{ template "web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
    - port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.deployment.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "web.name" . }}
    release: {{ .Release.Name }}
