
{{- if .Values.istio.serviceentry }}
{{- $name := include "dotnet.name" . }}
{{- $labels := include "dotnet.metaLabels" . }}
{{- $chart := include "dotnet.chart" . }}
{{- $namespace := .Release.Namespace}}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $serviceentry := .Values.istio.serviceentry }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{ $name }}-{{ $serviceentry.name }}"
  namespace: {{ $namespace }}
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  {{- toYaml $serviceentry.spec | nindent 2 }}
{{- end }}

{{- end }}