{{- if .Values.egress }}
{{- $name := include "dotnet.name" . }}
{{- $chart := include "dotnet.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $entry := .Values.egress.http }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "{{ $name }}-{{ $entry.name }}-http"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dotnet.metaLabels" . | nindent 4 }}
spec:
  hosts:
{{- range $t := $entry.targets }}
  - {{ $t.host }}
{{- end }}
  ports:
{{- range $t := $entry.targets }}
  - number: {{ $t.port | default "80" }}
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
{{- end }}
{{- end }}

{{- end }}