
{{- if .Values.istio.virtualservice }}
{{- $name := include "dotnet.name" . }}
{{- $labels := include "dotnet.metaLabels" . }}
{{- $chart := include "dotnet.chart" . }}
{{- $namespace := .Release.Namespace}}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $virtualservice := .Values.istio.virtualservice }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $name }}-{{ $virtualservice.name }}"
  namespace: {{ $namespace }}
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  {{- toYaml $virtualservice.spec | nindent 2 }}
{{- end }}

{{- end }}