{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "dotnet.name" . }}
  labels:
    app: {{ template "dotnet.name" . }}
    chart: {{ template "dotnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
spec:
  selector:
    matchLabels:
      app: {{ template "dotnet.name" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}