{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "dotnet.name" . }}
  labels:
    app: {{ template "dotnet.name" . }}
    chart: {{ template "dotnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
{{- if .Values.metrics.enabled }}
    prometheus: {{ .Values.metrics.prometheusInstance }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "dotnet.name" . }}
      release: {{ .Release.Name }}
  endpoints:
{{- if .Values.metrics.endpoints }}
{{ toYaml .Values.metrics.endpoints | indent 4 }}
{{- else }}
  - path: {{ .Values.metrics.endpointPath | default "/metrics" }}
    interval: {{ .Values.metrics.endpointInterval | default "15s" }}
    targetPort: {{ .Values.metrics.endpointTargetPort | default 8080 }}
    honorLabels: {{ .Values.metrics.endpointHonorLabels | default true }}
{{- if and (.Values.istio.enabled) (.Values.metrics.prometheusIstioMtlsEnabled) }}
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/istio.{{ .Values.metrics.prometheusIstioSecret }}/root-cert.pem
      certFile: /etc/prometheus/secrets/istio.{{ .Values.metrics.prometheusIstioSecret }}/cert-chain.pem
      keyFile: /etc/prometheus/secrets/istio.{{ .Values.metrics.prometheusIstioSecret }}/key.pem
      insecureSkipVerify: true
{{- end}}

{{- end }}
{{- end }}
