{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "dotnet.name" . }}
  labels:
    app: {{ template "dotnet.name" . }}
    chart: {{ template "dotnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
{{- if .Values.metrics.enabled }}
    prometheus: {{ .Values.metrics.prometheusInstance }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "dotnet.name" . }}
      release: {{ .Release.Name }}
  endpoints:
{{ toYaml .Values.metrics.endpoints | indent 4 }}
{{- end }}
