{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "dotnet.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "dotnet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appComponent }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/part-of: {{ .Values.appPartOf }}
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  hosts:
  {{- range .Values.istio.ingress.hosts }}
    - "{{ . }}"
  {{- end }}
  gateways:
{{- if .Values.istio.ingress.gateways }}
  {{- range .Values.istio.ingress.gateways }}
    - "{{ . }}"
  {{- end }}
{{- else }}
    - "{{ template "dotnet.name" . }}-gateway"
{{- end }}
  http:
  - match:
      - uri:
          prefix: {{ .Values.istio.ingress.path | default "/" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }} # can be omitted if its the only port for reviews
        host: "{{ template "dotnet.name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
      weight: 80
{{- end }}
