---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    {{- include "vault-injector.metaLabels" . | nindent 4 }}
webhooks:
  - name: vault.hashicorp.com
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    failurePolicy: {{ .Values.podsFailurePolicy }}
    clientConfig:
      service:
        name: vault-agent-injector-svc
        path: "/mutate"
        namespace: "{{ .Release.Namespace }}"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["deployments", "jobs", "pods", "statefulsets"]
    namespaceSelector:
      {{- if .Values.namespaceSelector.matchLabels }}
      matchLabels:
        {{ toYaml .Values.namespaceSelector.matchLabels | nindent 6 }}
      {{- end }}
      matchExpressions:
      {{- if .Values.namespaceSelector.matchExpressions }}
        {{ toYaml .Values.namespaceSelector.matchExpressions | nindent 6 }}
      {{- end }}
        - key: name
          operator: NotIn
          values:
            - {{ .Release.Namespace }}
