apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "golang.name" . }}
  labels:
    app: {{ template "golang.name" . }}
    chart: {{ template "golang.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "golang.name" . }}
      release: {{ .Release.Name }}
      version: {{ .Values.appVersion }}
  template:
    metadata:
      labels:
        app: {{ template "golang.name" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.appVersion }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end}}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          {{- if or (.Values.volumeMounts) (.Values.csi) }}
          volumeMounts:
          {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}
          {{- if .Values.csi }}
            - name: {{ .Values.csi.name }}
              mountPath: {{ .Values.csi.mountPath | quote }}
              readOnly: true
          {{- end }}
          {{- end }}
          ports:
          {{- range .Values.service.ports }}
          - name: {{ .name }}
            containerPort: {{ .targetPort }}
            protocol: TCP
          {{- end}}
{{- if and (.Values.liveness) (.Values.liveness.enabled) }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path | default "/" }}
              port: {{ .Values.liveness.port | default 8080 }}
{{- end }}
{{- if and (.Values.readiness) (.Values.readiness.enabled) }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path | default "/" }}
              port: {{ .Values.readiness.port | default 8080 }}
            initialDelaySeconds: {{ .Values.readiness.delay | default 15 }}
            timeoutSeconds: {{ .Values.readiness.timeout | default 15 }}
            periodSeconds: {{ .Values.readiness.periodSeconds | default 15 }}
{{- end }}
          env:
          - name: APP_ENV
            value: {{ .Values.appEnv }}
          {{- if .Values.secrets }}
{{ toYaml .Values.secrets | indent 10 }}
          {{- end }}
          {{- if .Values.environment }}
{{ toYaml .Values.environment | indent 10 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if or (.Values.volumes) (.Values.csi) }}
    volumes:
     {{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 6 }}
    {{- end }}
    {{- if .Values.csi }}
      - name: {{ .Values.csi.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.csi.name }}
    {{ end }}
  {{ end }}
