{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
{{- if not .Values.istio.ingress.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
{{- if .Values.istio.gatewayName }}
  name: {{ .Values.istio.gatewayName }}
{{- else }}
  name: {{ template "golang.name" . }}-gateway
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "golang.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appComponent }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/part-of: {{ .Values.appPartOf }}
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    istio: {{ .Values.istio.ingressGateway | default "ingressgateway" }} # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istio.ingress.hosts }}
      - {{ . }}
    {{- end }}
{{- if .Values.istio.ingress.tls.httpsRedirect }}
    tls:
      httpsRedirect: true
{{- end }}
{{- if .Values.istio.ingress.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    {{- range .Values.istio.ingress.hosts }}
      - {{ . }}
    {{- end }}
    tls:
      mode: SIMPLE
{{- if .Values.istio.ingress.tls.secretName }}
      credentialName: "{{ .Values.istio.ingress.tls.secretName  }}"
{{- else }}
      credentialName: "{{ template "golang.name" . }}"
{{- end }}
{{- end }}

{{- end }}
{{- end }}
