{{- if .Values.egress }}
{{- $name := include "golang.name" . }}
{{- $chart := include "golang.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $entry := .Values.egress.tcp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "{{ $name }}-{{ $entry.name }}-tcp"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golang.metaLabels" . | nindent 4 }}
spec:
  hosts:
{{- range $t := $entry.targets }}
  - {{ $t.host }}
{{- end }}
  ports:
{{- range $t := $entry.targets }}
  - number: {{ $t.port | default "443" }}
    name: tcp
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
{{- end }}
{{- end }}

{{- end }}