{{- if .Values.egress }}
{{- $name := include "golang.name" . }}
{{- $chart := include "golang.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $entry := .Values.egress.http }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $name }}-{{ $entry.name }}-http"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golang.metaLabels" . | nindent 4 }}
spec:
  hosts:
{{ range $t := $entry.targets }}
  - {{ $t.host }}
{{- end }}
  http:
    - timeout: 5s
{{ range $t := $entry.targets }}
      route:
        - destination:
            host: {{ $t.host }}
            port:
              number: {{ $t.port | default "80" }}
          weight: 100
{{- end }}
{{- end }}

{{- end }}