{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name}}-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golang.metaLabels" . | nindent 4 }}
spec:
  host: {{ template "golang.name" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}