{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name}}-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "golang.name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.appVersion }}
spec:
  host: {{ template "golang.name" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}