apiVersion: v1
kind: Service
metadata:
  name: {{ template "golang.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golang.metaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: {{ .Values.service.name | default "http" }}
    {{ if .Values.service.extraPorts }}
    {{ toYaml .Values.service.extraPorts | nindent 12 }}
    {{- end }}
  selector:
    {{- include "golang.selectorLabels" . | nindent 4 }}