apiVersion: v1
kind: Service
metadata:
  name: {{ template "golang.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golang.metaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "golang.selectorLabels" . | nindent 4 }}