{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name}}-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ template "nodejs.name" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}}