
{{- if .Values.istio.virtualservice }}
{{- $name := include "libchart.name" . }}
{{- $labels := include "libchart.labels" . }}
{{- $chart := include "libchart.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $virtualservice := .Values.istio.virtualservice }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $name }}-{{ $virtualservice.name }}"
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  {{- toYaml $virtualservice.spec | nindent 2 }}
{{- end }}

{{- end }}
