{{- if .Values.egress }}
{{- $name := include "nodejs.name" . }}
{{- $chart := include "nodejs.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $entry := .Values.egress.https }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $name }}-{{ $entry.name }}-https"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodejs.metaLabels" . | nindent 4 }}
spec:
  hosts:
{{ range $t := $entry.targets }}
  - {{ $t.host }}
{{- end }}
  tls:
  - match:
{{ range $t := $entry.targets }}
    - port: {{ $t.port | default "443" }}
      sni_hosts:
      - {{ $t.host}}
{{- end }}
    route:
{{ range $t := $entry.targets }}
    - destination:
        host: {{ $t.host }}
        port:
          number: {{ $t.port | default "443" }}
      weight: 100
{{- end }}
{{- end }}

{{- end }}