{{- if .Values.istio.enabled }}
{{- if .Values.istio.policy }}
{{- $values := .Values }}
{{- $relase := .Release }}

{{ range $entry := .Values.istio.policy.jwt }}
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ $entry.name }}-jwk
spec:
  targets:
  - name: {{ $relase.name }}
    ports:
    - number: {{ $values.service.port }}
  origins:
  - jwt:
      issuer: {{ $entry.issuer }}
      jwksUri: {{ $entry.jwksUri }}
  principalBinding: USE_ORIGIN
  peers:
  - mtls: {}

{{- end }}

{{- end }}
{{- end }}