{{- if .Values.policy }}
{{- $name := include "nodejs.name" . }}
{{- $chart := include "nodejs.chart" . }}
{{- $release := .Release }}
{{- $values := .Values }}

{{ range $entry := .Values.policy.jwt }}
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ $entry.name }}
spec:
  targets:
  - name: {{ $release.Namespace }}
  origins:
  - jwt:
      issuer: {{ $entry.issuer }}
      jwksUri: {{ $entry.jwksUri }}
  principalBinding: USE_ORIGIN
{{- end }}

{{- end }}