{{- if .Values.traefikV2.enabled }}
{{- $name := include "libchart.name" . }}
{{- $labels := include "libchart.labels" . }}
{{ range $i := .Values.traefikV2.ingressRoutes }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $name }}-{{ $i.name }}"
  {{- if $i.annotations }}
  annotations:
  {{ toYaml $i.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml $i.spec | nindent 2 }}
{{- end }}
{{- end }}
