{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "nodejs.name" . }}
  labels:
    app: {{ template "nodejs.name" . }}
    chart: {{ template "nodejs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
    - "{{ . }}"
  {{- end }}
  gateways:
{{- if .Values.istio.ingress.gateways }}
  {{- range .Values.istio.ingress.gateways }}
    - "{{ . }}"
  {{- end }}
{{- else }}
    - "{{ template "nodejs.name" . }}-gateway"
{{- end }}
  http:
  - match:
      - uri:
          prefix: {{ .Values.istio.ingress.path | default "/" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }} # can be omitted if its the only port for reviews
        host: "{{ template "nodejs.name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
      weight: 80
{{- end }}
