{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "nodejs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodejs.metaLabels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.ingress.hosts }}
    - "{{ . }}"
  {{- end }}
  gateways:
{{- if .Values.istio.ingress.gateways }}
  {{- range .Values.istio.ingress.gateways }}
    - "{{ . }}"
  {{- end }}
{{- else }}
    - "{{ template "nodejs.name" . }}-gateway"
{{- end }}
  http:
  - match:
      - uri:
          prefix: {{ .Values.istio.ingress.path | default "/" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }} # can be omitted if its the only port for reviews
        host: "{{ template "nodejs.name" . }}.{{ .Release.Namespace }}.svc.cluster.local"
      weight: 80
{{- end }}
