{{- if .Values.alertRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "java.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java.metaLabels" . | nindent 4 }}
spec:
  groups:
{{ toYaml .Values.alertRules | indent 4 }}
{{- end }}
