{{- $hosts := .Values.cert.hosts -}}

{{- if and .Values.istio.enabled (.Values.istio.ingress.enabled) }}
{{ $hosts = .Values.istio.ingress.hosts }}
{{- else if .Values.ingress.enabled }}
{{ $hosts = .Values.ingress.hosts }}
{{- end }}

{{- if and .Values.cert.enabled ($hosts) }}

apiVersion: {{ .Values.certmanagerApiVersion }}
kind: Certificate
metadata:
  name: {{ template "java.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "java.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appComponent }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/part-of: {{ .Values.appPartOf }}
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
{{ toYaml .Values.cert.annotations | indent 4 }}
spec:
{{- if .Values.cert.secretName }}
  secretName: {{ .Values.cert.secretName }}
{{- else }}
  secretName: {{ template "java.name" . }}
{{- end }}
{{- if .Values.cert.duration }}
  duration: {{ .Values.cert.duration }}
{{- end }}
  renewBefore: {{ .Values.cert.renewBefore }}
  commonName: {{ index $hosts 0 }}
  dnsNames:
{{ $hosts | toYaml | indent 4 }}
  issuerRef:
    name: {{ .Values.cert.issuer | default "letsencrypt-prod" }}
    kind: {{ .Values.cert.issuerKind | default "ClusterIssuer" }}
{{- end }}