{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "java.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java.metaLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "java.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}