{{- if .Values.csi -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.csi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "java.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appComponent }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/part-of: {{ .Values.appPartOf }}
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.csi.storage | default "10Mi" | quote }}
  volumeName: {{ .Values.csi.name }}
  storageClassName: {{ .Values.csi.storageClassName| quote}}
{{- end -}}