apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-{{ .Values.job.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronjob.metaLabels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  {{- if .Values.job.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  {{- end}}
  schedule: {{ .Values.job.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "cronjob.metaLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
        {{- if .Values.podAnnotations }}
          annotations:
          {{ toYaml .Values.podAnnotations | indent 4 }}
        {{- end }}
          labels:
            {{- include "cronjob.metaLabels" . | nindent 12 }}
            {{- if .Values.istio.enabled }}
            security.istio.io/tlsMode: istio
            service.istio.io/canonical-name: "{{ .Release.Name }}-{{ .Values.job.name }}"
            service.istio.io/canonical-revision: v1
            {{- end }}
        spec:
          restartPolicy: {{ .Values.job.restartPolicy | default "Never" }}
          containers:
            - name: "{{ .Release.Name }}-{{ .Values.job.name }}"
              env:
              - name: APP_ENV
                value: {{ .Values.appEnv }}
            {{-  if .Values.environment }}
{{ toYaml .Values.environment | indent 14 }}
            {{- end}}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always