apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-{{ .Values.job.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronjob.metaLabels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  {{- if .Values.job.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  {{- end}}
  schedule: {{ .Values.job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Release.Name }}-{{ .Values.job.name }}"
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            {{- if .Values.image.pullSecrets }}
            imagePullSecrets:
            {{- range $pullSecret := .Values.image.pullSecrets }}
              - name: {{ $pullSecret }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.volumeMounts) (.Values.csi) }}
            volumeMounts:
            {{- if .Values.volumeMounts }}
            {{ toYaml .Values.volumeMounts | indent 12 }}
            {{- end }}
            {{- if .Values.csi }}
              - name: {{ .Values.csi.name }}
                mountPath: {{ .Values.csi.mountPath | quote }}
                readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.job.args }}
            args:
              {{- range $arg := .Values.job.args }}
              - {{ $arg }}
              {{- end }}
            {{- end }}
            {{- if .Values.job.command }}
            command: {{ .Values.job.command }}
            {{- end }}
            env:
              - name: APP_ENV
                value: {{ .Values.appEnv }}
              {{- if .Values.secrets }}
              {{ toYaml .Values.secrets | indent 10 }}
              {{- end }}
              {{- if .Values.environment }}
              {{ toYaml .Values.environment | indent 10 }}
              {{- end }}
          restartPolicy: OnFailure
