apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "golang-istio.fullname" . }}
  labels:
    app: {{ template "golang-istio.fullname" . }}
    chart: {{ template "golang-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "golang-istio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "golang-istio.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default 80 }}
              protocol: TCP
{{- if .Values.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path | default "/" }}
              port: {{ .Values.liveness.port | default 80 }}
{{- end }}
{{- if .Values.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path | default "/" }}
              port: {{ .Values.readiness.port | default 80 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
