{{- if .Values.istio.enabled -}}
{{- if not .Values.istio.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "golang-istio.fullname" . }}-gateway
  labels:
    app: {{ template "golang-istio.fullname" . }}
    chart: {{ template "golang-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.version }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istio.hosts }}
      - {{ . }}
    {{- end }}
{{- end }}
{{- end }}