{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "golang-istio.fullname" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "golang-istio.name" . }}
    chart: {{ template "golang-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
spec:
  selector:
    matchLabels:
      app: {{ template "golang-istio.fullname" . }}
      release: {{ .Release.Name }}
  endpoints:
{{ toYaml .Values.metrics.endpoints | indent 4 }}
{{- end }}