apiVersion: v1
kind: Service
metadata:
  name: {{ template "golang-istio.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "golang-istio.name" . }}
    chart: {{ template "golang-istio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.appVersion }}
{{- if .Values.metrics.enabled }}
    prometheus: {{ .Values.metrics.prometheusInstance }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "golang-istio.name" . }}
    release: {{ .Release.Name }}
