name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: v2.16.0-rc.2
      HELM_TMP_DIR: /tmp/helm-tmp-package
      HELM_PUB_DIR: release

    steps:
    - uses: actions/checkout@v1
    - name: Helm Install
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
          | tar vxz \
            && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
            && rm -vrf linux-amd64
    - name: Helm Init
      run: helm init --client-only --kubeconfig=$HOME/.kube/kubeconfig
    - name: Helm Lint
      run: ./helm-test.sh

    # Package
    - name: Helm Package
      run: |
        mkdir -p ${HELM_TMP_DIR}
        ./helm-package.sh ${HELM_TMP_DIR}
        ls -la ${HELM_TMP_DIR}

    # Publish
    - uses: actions/checkout@v1
      with:
        ref: gh-pages
        path: ./release
    - name: Helm Publish
      run: |
        ls -la ${HELM_TMP_DIR}
        for chart in ${HELM_TMP_DIR}/*; do
          chart=$(basename $chart)

          mv -vn ${HELM_TMP_DIR}/${chart} ${HELM_PUB_DIR}/${chart}

          helm repo index .
        done
    - name: Git Push
      run: |
        if [git diff-index --quiet HEAD -- ${HELM_PUB_DIR}]; then
          git add index.yaml
          git add ${HELM_PUB_DIR}
          git status
          git commit -am "AUTO-RELEASE: release Helm Charts from ${GITHUB_SHA}"
        else
          echo "No new packages to push"
        fi
