name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Helm
      env:
        HELM_VERSION: v2.16.0-rc.2
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
          | tar vxz \
            && mv -v linux-amd64/helm /bin/helm \
            && rm -vrf linux-amd64
