name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/master'

    env:
      HELM_VERSION: v2.16.0-rc.2
      HELM_TMP_DIR: /tmp/helm-tmp-package
      HELM_PUB_DIR: release

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Helm Install
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
          | tar vxz \
            && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
            && rm -vrf linux-amd64
    - name: Helm Init
      run: helm init --client-only --kubeconfig=$HOME/.kube/kubeconfig

    # Package
    - name: Helm Package
      run: |
        mkdir -p ${HELM_TMP_DIR}
        ./helm-package.sh ${HELM_TMP_DIR}
        ls -la ${HELM_TMP_DIR}

    # Publish
    - uses: actions/checkout@v1
      with:
        ref: gh-pages
        path: ./release
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Helm Publish
      run: |
        ls -la ${HELM_TMP_DIR}
        for chart in ${HELM_TMP_DIR}/*; do
          chart=$(basename $chart)
          echo $chart

          if [ ! -f "${HELM_PUB_DIR}/${chart}" ]; then
            mv -vn "${HELM_TMP_DIR}/${chart}" "${HELM_PUB_DIR}/${chart}"
          else
            echo "Chart $chart is already released!"
          fi

          helm repo index .
        done

    - name: Git Push
      run: |
        git add -v ${HELM_PUB_DIR}
        git status
        if ! $(git diff-index --quiet HEAD -- ${HELM_PUB_DIR}/*); then
          git add -v index.yaml
          git status
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git commit -am "AUTO-RELEASE: publish Helm Charts from master@${GITHUB_SHA:0:7}"

          git push "https://${{ secrets.GITHUB_PAT }}@github.com/${GITHUB_REPOSITORY}.git"
        else
          echo "No new packages to push"
        fi
