name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: v3.0.2
      CONFTEST_VERSION: "0.15.0"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Conftest Install
        run: |
          curl -sSL https://github.com/instrumenta/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz \
            | tar vxz \
              && sudo mv -v conftest /usr/local/bin/conftest
      - name: Install YQ
        run: |
          curl -sSL https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 -o yq && chmod +x yq && sudo mv yq /usr/local/bin
      - name: Helm Install
        run: |
          curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
            | tar vxz \
              && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
              && rm -vrf linux-amd64
      - name: Test & Lint
        run: ./helm-test.sh
      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -output json temp/"
